main: SocketFactory.cc main.cc UDP.cc TCPConnListner.cc TCPConn.cc
	g++ -o main SocketFactory.cc main.cc UDP.cc Action.cc ThreadPool.h TCPConnListner.cc TCPConn.cc -I. -g

object = SocketFactory.o main.o UDP.o